openapi: 3.0.3
info:
  title: ping-pong
  version: 1.0.0
  description: An API that returns pong
paths:
  /ping:
    get:
      description: Return a String pong
      responses:
      "200":
        content:
          text/plain:
            schema:
              type: string
              example: pong
