openapi: 3.0.0
info:
  title: JSON intro.
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get all users
      parameters:
        - in: query
          name: page
          schema:
            type: string
          required: false
          description: Number of page
        - in: query
          name: size
          schema:
            type: string
          required: false
          description: Number of users in a page
