openapi: 3.0.0
info:
  title: TaskAPI
  description: API to manage tasks.
  version: 1.0.0
  contact:
    name: NickyHariniaina
    email: nickyharini1na@gmail.com
  license:
    name: MIT

servers:
  - url: http://localhost:8080
    description: Localhost URL

paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        "200":
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"

    post:
      summary: Create new tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: List of created tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"

    delete:
      summary: Delete multiple tasks
      parameters:
        - name: ids
          description: A list of tasks id
          in: query
          required: true
          schema:
            type: array
            items:
              type: integer
      responses:
        "200":
          description: List of deleted tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"

  /tasks/{id}:
    get:
      summary: Get task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Task found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Task not found

    delete:
      summary: Delete a task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Task deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "404":
          description: not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Task not found

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Buy groceries
        completed:
          type: boolean
          example: false
      required:
        - id
        - title
        - completed
